name: CI/CD

on:
  push:
    branches: [ '**' ] # this triggers only on branch commits, which prevents triggering off of tag-only commits
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      semver: ${{ steps.parse.outputs.semver }}
      releasable: ${{ steps.parse.outputs.releasable }}
      tag-exists: ${{ steps.parse.outputs.tag-exists }}
    steps:
      - uses: actions/checkout@v3
      - uses: pkgxdev/dev@v0
      - name: Parse version
        id: parse
        uses: ./.github/actions/version
        with:
          semver: ${{ env.VERSION }}
      - run: echo "${{ toJSON(steps) }}"

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build-tar-image
        with:
          build-file: .github/Dockerfile
          build-context: .

  e2e-tests:
    needs: [ build ]
    strategy:
      fail-fast: false
      matrix:
        data:
          - name: "return"
            script: |
              "return"
            expected: "return"

          - name: "context"
            script: |
              Map.keys(context)
            expected: "[__struct__,action,actor,api_url,event_name,graphql_url,job,payload,ref,run_id,run_number,server_url,sha,workflow]"
    runs-on: ubuntu-latest
    name: "e2e tests (${{ matrix.data.name }})"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/load-tar-image
      - uses: ./.github/actions/run-e2e
        with:
          image-name: ${{ env.IMAGE_NAME }}
          script: ${{ matrix.data.script }}
          expected: ${{ matrix.data.expected }}

  push:
    name: ${{ needs.version.outputs.releasable == 'true' && 'push' || 'push (dry-run)' }}
    runs-on: ubuntu-latest
    needs: [ version, build, e2e-tests ]
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v3
      - uses: ./.github/actions/load-tar-image
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - uses: ./.github/actions/push-tar-image
        with:
          source-image: ${{ env.IMAGE_NAME }}
          semver: v${{ needs.version.outputs.semver }}
          exists: v${{ needs.version.outputs.tag-exists }}
          push: ${{ needs.version.outputs.releasable }}

  release:
    needs: [ version, push ]
    if: needs.version.outputs.releasable == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          prerelease: true
          tag_name: v${{ needs.version.outputs.semver }}
          token: ${{ secrets.PAT }} # using our own PAT so other workflows run
