name: Examples

on:
  push:
    paths:
      - .github/workflows/examples.yml
  release:
    types:
      - "created"
  workflow_dispatch:

jobs:
  io-visible-in-logs-and-return-value-available-via-outputs:
    runs-on: ubuntu-latest
    steps:
      - uses: gaggle/elixir_script@v0
        id: script
        with:
          script: |
            IO.puts("Hello world")
            "return"

      - name: Get result
        run: echo "${{steps.script.outputs.result}}"
